name: Archive Threads Posts

on:
  workflow_dispatch:
  schedule:
    - cron: "17 0,6,12,18 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: write credentials
        run: |
          cat <<'EOF' > service_account.json
          ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          EOF

      - name: run script
        env:
          THREADS_ACCESS_TOKEN: ${{ secrets.THREADS_ACCESS_TOKEN }}
          TARGET_USERNAME: ${{ secrets.TARGET_USERNAME }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}

        run: python main.py
